//用户注册
export const USER_REGIST_FIELD = "USER_REGIST_FIELD";//用户注册信息同步
export const USER_REGIST_RESULT = "USER_REGIST_RESULT"//用户注册结果
export const USER_REGIST_UNLOAD = "USER_REGIST_UNLOAD" //注册组件卸载

// 登录
export const USER_LOGIN_FIELD = "USER_LOGIN_FIELD"  //用户登录状态同步
export const USER_LOGIN_RESULT = "USER_LOGIN_RESULT" //用户登录结果
export const USER_LOGIN_UNLOAD = "USER_LOGIN_UNLOAD" //登录组件卸载

//设置
export const SETTING_FIELD = "SETTING_FIELD" //状态信息同步
export const SETTING_UNLOAD = "SETTING_UNLOAD" //设置组件卸载
export const SETTING_RESULT = "SETTING_RESULT" //设置结果返回
export const SETTING_LOGOUT = "SETTING_LOGOUT" //退出设置

// 用户中心
export const PROFILE_GET_RESULT = "PROFILE_GET_RESULT" //获取用户信息结果
export const PROFILE_FOLLOW_RESULT = "PROFILE_FOLLOW_RESULT"//获取用户关注结果

// 文章列表
export const ARTICLE_AUTHOR_RESULT = "ARTICLE_AUTHOR_RESULT"
export const LIMIT = 5

// 单个文章
export const ARTICLE_UNLOAD = "ARTICLE_UNLOAD"
export const ARTICLE_CREATE_FIELD = "ARTICLE_CREATE_FIELD"
export const ARTICLE_ADD_TAG = "ARTICLE_ADD_TAG"
export const ARTICLE_REMOVE_TAG = "ARTICLE_REMOVE_TAG"
export const ARTICLE_CREATE_RESULT = "ARTICLE_CREATE_RESULT"
export const ARTICLE_GET_RESULT = "ARTICLE_GET_RESULT"

export const ARTICLE_DELETE_RESULT = "ARTICLE_DELETE_RESULT"
export const ARTICLE_FAVORITE_RESULT = "ARTICLE_FAVORITE_RESULT"
export const ARTICLE_UNFAVORITE_RESULT = "ARTICLE_UNFAVORITE_RESULT"
export const ARTICLE_UPDATE_RESULT = "ARTICLE_UPDATE_RESULT"

// 评论
export const COMMENT_CREATE_FILED = "COMMENT_CREATE_FILED"
export const COMMENT_GET_RESULT = "COMMENT_GET_RESULT"
export const COMMENT_DELETE_RESULT = "COMMENT_DELETE_RESULT"
export const COMMENT_CREATE_RESULT = "COMMENT_CREATE_RESULT"

// 标签
export const TAGS_GET_RESULT = "TAGS_GET_RESULT"

//Home
export const HOME_TAG_SYNC = "HOME_TAG_SYNC"
export const HOME_TAB_SYNC = "HOME_TAB_SYNC"
export const HOME_PAGE_SYNC = "HOME_PAGE_SYNC"
export const HOME_ARTICLES_RESULT = "HOME_ARTICLES_RESULT"

export const HOME_UNMOUNT = "HOME_UNMOUNT"